ProgLabHW7
ZarechOleksii/programmingPythonLabs pull request #17
Opened 2020-11-04 14:20 UTC by ZarechOleksii

2020-11-11 15:21 UTC, tetianastoyko requested changes

2020-11-11 15:21 UTC, tetianastoyko commented on ProgLabHW7/UnitTests.py
> +    def test_collection_sort_write(self):
зробіть цикл, тут багато копі пасту

2020-11-11 15:21 UTC, tetianastoyko commented on ProgLabHW7/UnitTests.py
> +    def test_history(self):
зробіть цикл, тут багато копі пасту

2020-11-11 15:21 UTC, tetianastoyko commented on ProgLabHW7/UnitTests.py
> +    def test_collection_sort_write(self):
загалом це стосується всього коду

2020-11-18 20:20 UTC, tetianastoyko requested changes

2020-11-18 20:20 UTC, tetianastoyko commented on ProgLabHW7/UnitTests.py
> +        self.test_dict['duration'] = 'abc'
зробіть dict/array і використайте цикл, це ж купа однакового коду

2020-11-18 20:20 UTC, tetianastoyko commented on ProgLabHW7/UnitTests.py
> +        self.test_dict['price'] = 'abc'
зробіть dict/array і використайте цикл, це ж купа однакового коду

2020-11-18 20:20 UTC, tetianastoyko commented on ProgLabHW7/UnitTests.py
> +        self.test_dict['price'] = 'abc'
test_validation_title - тут це добре зроблено

2020-11-18 20:20 UTC, tetianastoyko commented on ProgLabHW7/UnitTests.py
> +        test_dict = {'id': '1',
видаліть і використайте те об'єкт з 7 рядка

2020-11-18 20:20 UTC, tetianastoyko commented on ProgLabHW7/UnitTests.py
> +        self.assertFalse(test_collection.delete_id(57), 'Has to be false')
ну після видалення id = 57, ви маєте перевірити 2 колекції: 1 - ця колекція з якої видалили елемент, 2 - колекція, яка і не мала цього елемента

2020-11-18 20:20 UTC, tetianastoyko commented on ProgLabHW7/UnitTests.py
> +        self.assertFalse(test_collection.delete_id(57), 'Has to be false')
те саме стосується і редагування і додавання

2020-11-18 20:20 UTC, tetianastoyko commented on ProgLabHW7/UnitTests.py
> +    def test_collection_sort_write(self):
ну не виправили все

2020-11-18 20:20 UTC, tetianastoyko commented on ProgLabHW7/UnitTests.py
> +    def test_history(self):
використайте test_dict з 7 рядка, тут видаліть

2020-11-26 00:04 UTC, ZarechOleksii commented on ProgLabHW7/UnitTests.py
> +        self.assertFalse(test_collection.delete_id(57), 'Has to be false')
> ну після видалення id = 57, ви маєте перевірити 2 колекції: 1 - ця колекція з якої видалили елемент, 2 - колекція, яка і не мала цього елемента

Id 57 не було в колекції, тому воно ассертить false, а наступний рядок ID 1, він там є, тому ассертить true

2020-11-26 06:49 UTC, tetianastoyko approved these changes
+- ок

2020-11-26 08:17 UTC, merged